[book]
authors = ["Emre Ergun"]
language = "en"
multilingual = false
src = "src"
title = "C++ Explained"

[output.html]
git-repository-url="https://github.com/emre-ergun/mdbook-cpp"

[output.html.playground]
runnable = false
